CREATE USER IF NOT EXISTS root IDENTIFIED BY 'root';

DROP DATABASE IF EXISTS banka;
CREATE DATABASE banka DEFAULT CHARACTER SET utf8;

USE banka;

GRANT ALL ON banka.* TO 'root'@'%';

FLUSH PRIVILEGES;
